# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [5]:
import numpy as np
from models.NeuralNetwork import NeuralNetwork
nn = NeuralNetwork(
      learning_rate=0.01,
      discount_factor=0.99,
      architecture=np.array([4, 8, 4, 2])
)

nn.print_network()



NEURAL NETWORK STRUCTURE

Layer 0 (INPUT)
 Neurons: 4

Layer 1 (HIDDEN)
 Neurons: 8
 Weights shape: (8, 4)
 Weights:
[[0.062 0.316 0.071 0.955]
 [0.939 0.38  0.916 0.35 ]
 [0.238 0.971 0.165 0.59 ]
 [0.199 0.494 0.55  0.296]
 [0.993 0.544 0.791 0.103]
 [0.447 0.143 0.239 0.827]
 [0.225 0.476 0.314 0.773]
 [0.943 0.921 0.749 0.447]]
 Bias shape: (8, 1)
 Bias:
[[0.42 ]
 [0.775]
 [0.94 ]
 [0.024]
 [0.148]
 [0.318]
 [0.397]
 [0.659]]
--------------------------------------------------

Layer 2 (HIDDEN)
 Neurons: 4
 Weights shape: (4, 8)
 Weights:
[[0.396 0.904 0.896 0.001 0.959 0.645 0.732 0.079]
 [0.574 0.95  0.688 0.016 0.92  0.056 0.194 0.955]
 [0.51  0.058 0.707 0.181 0.433 0.394 0.706 0.263]
 [0.405 0.125 0.608 0.803 0.391 0.583 0.666 0.805]]
 Bias shape: (4, 1)
 Bias:
[[0.085]
 [0.278]
 [0.352]
 [0.695]]
--------------------------------------------------

Layer 3 (OUTPUT)
 Neurons: 2
 Weights shape: (2, 4)
 Weights:
[[0.172 0.563 0.963 0.414]
 [0.383 0.753 0.517 0.503]]
 Bias shape: 